import pyautogui

INVESTOR_BANNER_HEIGHT = 250
PORTFOLIO_SCREEN_HEADER = 176
SCREEN_WIDTH, SCREEN_HEIGHT = pyautogui.size() 
SCROLL_CLICK_LENGTH = 138
SHARE_HEIGHT = 58
SHARE_SCREEN_HEADER = 358
SIDEBAR_WIDTH = 136

INIT_WAIT = 5
LOAD_PAGE_WAIT = 3
SCROLL_WAIT = 1