import pyautogui

SCREEN_WIDTH, SCREEN_HEIGHT = pyautogui.size() 
SCROLL_CLICK_LENGTH = 120
SIDEBAR_WIDTH = 136
INVESTOR_HEIGHT = 63
SEARCH_BANNER_HEIGHT = 280
SEARCH_SCREEN_FIRST_INDENT = 191
SEARCH_SCREEN_HEADER = 423
PORTFOLIO_BUTTON_X = 740
PORTFOLIO_BUTTON_Y = 360
INVESTOR_BANNER_HEIGHT = 250
SHARE_HEIGHT = 57

DOWNLOAD_WAIT = 8
INIT_WAIT = 5
INFINITE_SCROLL_WAIT = 0.5
LOAD_PAGE_WAIT = 1
POPUP_WAIT = 3
SCROLL_WAIT = 1

HTML_SAVE_DIR = "/home/utnubu/Downloads"