import pyautogui

INVESTOR_BANNER_HEIGHT = 250
INVESTOR_HEIGHT = 63
PORTFOLIO_SCREEN_HEADER = 176
SCREEN_WIDTH, SCREEN_HEIGHT = pyautogui.size() 
SCROLL_CLICK_LENGTH = 138
SEARCH_BANNER_HEIGHT = 280
SEARCH_SCREEN_FIRST_INDENT = 182
SEARCH_SCREEN_HEADER = 423
SHARE_HEIGHT = 58
SHARE_SCREEN_HEADER = 358
SIDEBAR_WIDTH = 136

DOWNLOAD_WAIT = 8
INIT_WAIT = 5
LOAD_PAGE_WAIT = 8
POPUP_WAIT = 8
SCROLL_WAIT = 1

HTML_SAVE_DIR = "Downloads"